### ISSUE TITLE
[BE]회원정보 조회

### ISSUE THREAD

**Issue by syw2858** [MultiProject23/Shop_SemiProject#13]
# 개요

로그인 되어있는 회원의 회원정보(이메일, 이름, 생년월일, 전화번호)를 불러와서 화면에 보여주는 기능

## 해결책

로그인이 되어있는 상태인지 검사
되어있으면 계정에 입력되어있는 회원정보를 불러와서
화면에 조회

## 할 일

로그인 되어있는 상태인지 묻고
되어있다면 `select * from db where email={로그인 된 이메일}`
연동된 정보를 불러와서 화면에 출력

**Comment by KIMSEI1124** [comment]
# 설명

## 피드백

URI : `/auth/member` - GET
`where` : member table 에 있는 `id`로 체크

## 필요한 데이터

```java
    private String name;
    private String email;
    private String phoneNumber;
```
