### ISSUE TITLE
[BE] 상품 정보 조회 구현

### ISSUE THREAD

**Issue by rrimm** [MultiProject23/Shop_SemiProject#14]
# 개요

- 상품 상세페이지 내부에 상품의 이름, 가격 등의 데이터를 가져오는 기능
- 상품 상세페이지에서 사용자가 추가한 상품의 정보를 보내는 기능
- 상품 상세페이지 내부에 해당 상품과 연관된 상품의 데이터를 가져오는 기능

## 해결책

상품 상세페이지에서 사용자가 추가한 상품의 수량이 상품의 재고보다 많은지 여부 검사

## 할 일

- 상품 정보 조회 비즈니스 로직 구현
- 사용자가 상품을 추가하는 기능 비즈니스 로직 구현
- 연관 상품 정보 조회 비즈니스 로직 구현
- 재고 부족에 대한 메시지 처리 기능 구현

**Comment by KIMSEI1124** [comment]
# 설명

상품 상세페이지에 대한 설명입니다.

## 제품 데이터

제품의 상세 데이터 입니다.

### URI

컨트롤러의 해당 `URI`는  `/api/product/{id}` 입니다.

### request

클라이언트측에서 넘어오는 정보는 해당 제품의 고유 식별자인 `id` 가 `Long` 타입으로 넘어옵니다.

### response

서버에서 클라이언트로 보내야할 데이터는 다음과 같습니다.

```java
    private Long id;
    private String name;
    private String image;
    private int price;
    private String info;
    private int stock;
    private Category category;
    private Target target;
    private List<String> carousel;
```

## 연관 상품 데이터

상세 제품의 연관 상품 데이터 입니다.

### URI

컨트롤러의 해당 `URI` 는 `/api/product/related/{id}` 입니다.

### request

클라이언트측에서 넘어오는 정보는 해당 제품의 고유 식별자인 `id` 가 `Long` 타입으로 넘어옵니다.

### response

서버에서 클라이언트로 보내야할 데이터는 다음과 같습니다.
```java
    private Long productId;
    private String image;
    private String name;
    private int price;
```
다음과 같은 형태로 리스트로 보내야 합니다.
리스트의 크기는 적절하게 잡아 주시고 카테고리 혹은 타켓을 가지고 연관 지어주시면 좋습니다.
