### ISSUE TITLE
[BE] 장바구니 등록 - post

### ISSUE THREAD

**Issue by paul3148** [MultiProject23/Shop_SemiProject#15]
# 개요
장바구니에 사용자가 선택한 물건 등록

## 할 일

- 장바구니에 원하는 물건 등록
- 선택한 수량에 맞게 장바구니에 등록
- 이미 장바구니에 있는 상품일 경우 "이미 장바구니에 있는 상품입니다" 경고창 출력 후 등록되지 않음
- 옵션을 선택하지 않은 경우 "옵션을 선택해 주세요" 경고창 출력

**Comment by KIMSEI1124** [comment]
# 설명

제품을 장바구니에 저장할 때의 설명입니다.

## URI

해당 컨트롤러의 URI는 `/auth/cart` - Post 입니다.

## request

클라이언트 측에서 보내는 `JSON` 의 형태는 다음과 같습니다.
```json
{
  "productId" : 1,
  "memberId" : 1,
}
```
저장할 때 사용하는 필요한 데이터는 다음과 같습니다.
```java
    private Long productId;
    private Long memberId;
    private boolean checked;
    private int quantity;
```
참고로 `checked`는 기본 값이 `true` 이며, `quantity` 의 기본 값은 `1`로 고정입니다.

## response

클라이언트측으로 보내야할 정보는 `http.ok` 인 `200` 번 응답 번호 입니다. 

## 예외 처리

예외 처리 관련은 아직 미뤄 두시고 주석으로만 달아두세요.
