### ISSUE TITLE
[BE] DB 스키마 수정

### ISSUE THREAD

**Issue by KIMSEI1124** [MultiProject23/Shop_SemiProject#97]
# 개요

`varchar` 의 데이터 특성으로 인하여 최적화가 필요하다.

## 해결책

적절한 값의 크기를 정한다.

## 할 일

- `Member`
- `Product`
- `Order`
- `review`

**Comment by syw2858** [comment]
Member

- id - biginit
- birth - date 
- Email - varchar(50)
- Name - varchar(20)
- Password - varchar(16)
- Phone - varchar(13)
- Role - varchar(20)

**Comment by rrimm** [comment]
# 개요
 스키마 수정 제안 - Product

# 내용

```
create table product
(
    id       bigint auto_increment primary key,
    category varchar(10) not null,
    image    mediumblob   not null,
    info     varchar(255) not null,
    name     varchar(100) not null,
    price    int          not null,
    stock    int          not null,
    target   varchar(10) not null
);
```
# 상세
```
id: bigint 
category: varchar(10)
image: mediumblob
info: varchar(255) 
name: varchar(100) 
price: int  
stock: int 
target: varchar(10) 
```


# 근거
예시)
SELECT * FROM PRODUCT WHERE CHAR_LENGTH(INFO) >{**최적화할 숫자**}; 
명령문을 실행하여 최적화 크기 확인

**Comment by rrimm** [comment]
# 개요
 스키마 수정 제안 - Orders
 
 # 내용
```
id: bigint
date: date
quantity: int
order_status: varchar(20)
member_id: bigint
product_id: bigint
```

# 근거

Status 클래스에서 가장 긴 문자열: ORDER_CONFIRMATION 
select char_length('ORDER_CONFIRMATION'); 명령문 실행 시 값 18.

**Comment by rrimm** [comment]
# 개요
 스키마 수정 제안 - Review
 
 # 내용
```
id: bigint
category: varchar(10)
content: varchar(250)
image: mediumblob
member_id: bigint
product_id: bigint
```
